Update logcapture.yml
Found that sometimes the curl fails but doesn't exit with an error. (for example if the token is expired, the HTTP response is 401 but curl exits with no error code.)

Added some logic to immediately fail the action if the curl results in anything other than "200".

diff --git a/logcapture.yml b/logcapture.yml
--- a/logcapture.yml
+++ b/logcapture.yml
@@ -19,6 +19,11 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
+      # Test the API using TOKEN and fail immediately if not http 200
+      - name: Test the TOKEN and API
+        run: |
+          if [ $(curl --silent -H "Authorization: token ${{ secrets.PAT_TOKEN }}" https://api.github.com/orgs/${{ secrets.ORG_NAME }}/audit-log --write-out "%{http_code}" --output /dev/null) -ne 200 ]; then echo "HTTP Response NOT 200, Check CURL and TOKEN"; exit 1; else echo "HTTP Response 200 received assumed PAT and CURL are good"; fi
+
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
